### ISSUE TITLE
Make sure it supports empty nodes

### ISSUE THREAD

**Issue by ftyers** [keggsmurph21/notatrix#1]
e.g. 5.1 below. See: http://universaldependencies.org/format.html

```
1      Sue       Sue
2      likes     like
3      coffee    coffee
4      and       and
5      Bill      Bill
5.1    likes     like
6      tea       tea
```

**Comment by keggsmurph21** [comment]
Does CG3 support this?

**Comment by ftyers** [comment]
@keggsmurph21 no. This is something that is just in CoNLL-U.

**Comment by keggsmurph21** [comment]
see  59f17c0 .. hopefully that addresses this issue. let me know if there are more concerns :)
