### ISSUE TITLE
Should maintain split surface forms when switching between formats

### ISSUE THREAD

**Issue by ftyers** [keggsmurph21/notatrix#2]
For example, let's say you start out with a CoNLL-U format tree:

```
# sent_id = _
# text = I wanna skate .
1	I	I	_	prn	_	_	_	_	_
2-3	wanna	_	_	_	_	_	_	_	_
2	wan	want	_	vblex	_	_	_	_	_
3	na	to	_	pr	_	_	_	_	_
4	skate	skate	_	vblex	_	_	_	_	_
5	.	_	PUNCT	_	_	_	_	_	_
```

And you switch to CG3:

```
"<I>"
        "I" prn
"<wanna>"
        "want" vblex
                "to" pr
"<skate>"
        "skate" vblex
"<.>"
        "." sent
```

Note that the split surface forms "wan" "na" are not represented in the CG3 format. They should be maintained in the data structure, so that when you switch back you don't get `_`

**Comment by keggsmurph21** [comment]
Currently it'll just throw an exception if you try to convert to an incompatible format. Make sense that we should have some surface form available, probably as read-only

**Comment by ftyers** [comment]
The behaviour should probably be:

1) If you start in CoNLL-U and have the split forms, and switch to CG3 then it saves them, so when you switch back they are still there.
2) If you start in CG3 and switch to CoNLL-U and the forms are missing they should be `_`, then if you fill them out in CoNLL-U it should save them and behave like in (1).

**Comment by keggsmurph21** [comment]
this has been working for a while.... here's a demonstration that works in the node REPL or browser:

```javascript
> const nx = require('notatrix');
> const s = new nx.Sentence(`# sent_id = _
# text = I wanna skate .
1	I	I	_	prn	_	_	_	_	_
2-3	wanna	_	_	_	_	_	_	_	_
2	wan	want	_	vblex	_	_	_	_	_
3	na	to	_	pr	_	_	_	_	_
4	skate	skate	_	vblex	_	_	_	_	_
5	.	_	PUNCT	_	_	_	_	_	_`);
> console.log(s.to('CoNLL-U').output);
# sent_id = _
# text = I wanna skate .
1	I	I	_	prn	_	_	_	_	_
2-3	wanna	_	_	_	_	_	_	_	_
2	wan	want	_	vblex	_	_	_	_	_
3	na	to	_	pr	_	_	_	_	_
4	skate	skate	_	vblex	_	_	_	_	_
5	.	_	PUNCT	_	_	_	_	_	_
> console.log(s.to('CG3').output);
# sent_id = _
# text = I wanna skate .
"<I>"
	"I" prn #1->
"<wanna>"
	"want" vblex #2->
		"to" pr #3->
"<skate>"
	"skate" vblex #4->
"<.>"
	"." PUNCT #5->
> console.log(s.to('CoNLL-U').output);
# sent_id = _
# text = I wanna skate .
1	I	I	_	prn	_	_	_	_	_
2-3	wanna	_	_	_	_	_	_	_	_
2	wan	want	_	vblex	_	_	_	_	_
3	na	to	_	pr	_	_	_	_	_
4	skate	skate	_	vblex	_	_	_	_	_
5	.	_	PUNCT	_	_	_	_	_	_
```
