### ISSUE TITLE
Come up with a way to not rely on token ID explicitly

### ISSUE THREAD

**Issue by ftyers** [keggsmurph21/notatrix#3]
A big problem with dealing with ambiguous analyses in CG format is that it makes dealing with the token IDs/numbering more difficult because the numbering can differ depending on which combination of subtokens is chosen. 

Consider the following example:

```
"<I>"
        "I" prn subj p1 mf sg
"<wanna>"
        "want to" vbmod pres
        "want" vblex pres
                "to" pr
"<skate>"
        "skate" n sg
        "skate" vblex inf
        "skate" vblex pres
        "skate" vblex imp
"<.>"
        "." sent
```

The problem here is that the ID of "skate" will be different depending on if you choose "want to" as a modal verb or "want" + "to". e.g. it could be:

```
1	I	I	_	prn	subj|p1|mf|sg
2	wanna	want to	_	vbmod	pres
3	skate	skate	_	n	sg
4	.	.	_	sent	_
```

Or:

```
1	I	I	prn	_	subj|p1|mf|sg	_	_	_	_
2-3	wanna	_	_	_	_	_	_	_	_
2	_	want	vblex	_	pres	_	_	_	_
3	_	to	pr	_	_	_	_	_	_
4	skate	skate	n	_	sg	_	_	_	_
5	.	.	sent	_	_	_	_	_	_
```

**Comment by keggsmurph21** [comment]
This is already handled by the design of the data structure. Basically it's a graph with a `tokens` array, where each `Token` holds an array of `analyses`, and each `Analysis` holds an array of `subTokens`.

Every time we need to serialize it to CoNLL-U or CG3, the sentence runs an `index` method before serializing each analysis/token. For example, the `head` and `deps` on each token are just getters for an underlying `_heads` and `_deps` arrays (of pointers to `Token`s, so indexing those isn't a problem.

**Comment by keggsmurph21** [comment]
)
